parameters:
  - name: customCommand
    type: string
    default: install
    values: 
      - install
      - run build

stages:
  - stage: nodejs
    displayName: nodejsbuild
    jobs:
      - job: node
        displayName: nodejsbuild1
        steps: 
          - task: Npm@1
            inputs: 
              command: 'custom'
              customCommand: "${{ parameters.customCommand }}"
              workingDir: $(Build.SourcesDirectory)
           




