parameters:
  - name: customCommand
    type: string
    default: install
    values: 
      - build
      - install

stages:
  - stage: nodejs
    displayName: nodejsbuild
    jobs:
      - job: node
        displayName: nodejsbuild1
        steps: 
          - task: Npm@1
            inputs: 
              command: 'custom'
              customCommand: 'run build'
           




